### ISSUE TITLE
Issue in setting H5Pset_dxpl_mpio

### ISSUE THREAD

**Issue by skim0119** [iraikov/neuroh5#2]
## Description

For small network cases, I'm consistently getting the error like below:

```sh
append_edge_attribute: error in H5Pset_dxpl_mpio: Assertion 'status >= 0' failed in file '/opt/neuroh5/include/hdf5/hdf5_edge_attributes.hh' line 126
terminate called after throwing an instance of 'AssertionFailureException'
  what():  append_edge_attribute: error in H5Pset_dxpl_mpio: Assertion 'status >= 0' failed in file '/opt/neuroh5/include/hdf5/hdf5_edge_attributes.hh' line 126
```

I believe the bug is when `size=1`, because `H5Pset_dxpl_mpio` will not be called while `throw_assert` will still check uninitialized `status >= 0`.

## Location
https://github.com/iraikov/neuroh5/blob/ad5dc7d9b334c949ac3a5049626052b2d82d78c3/include/hdf5/hdf5_edge_attributes.hh#L122-L127

## Suggestion

Move `throw_assert` inside the `if` block, or initialize `status` beforehand. I believe the purpose of `throw_assert` is to check if `H5Pset_dxpl_mpio` is correctly set, so it only needs to check inside the if-block.

**Comment by iraikov** [comment]
Right, status is potentially uninitialized. I will remove the size check, I don't think it is really necessary. Thanks for reporting this,

**Comment by skim0119** [comment]
I checked the issue is resolved on my end. Thank you!
